spring:
  application:
    name: fegin-server

server:
  port: 8901

eureka:
  instance:
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: register.center.com
    server:
      port: 8051
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka/
