server:
  port: 6666

spring:
  application:
    name: msa-store-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    admin:
      path: /store-admin/**
      serviceId: msa-store-admin

