server:
  port: 8888

spring:
  application:
    name: microservice-store-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
#  sensitiveHeaders:
#  sensitiveHeaders: "*"  #敏感headers也支持全局设置(必须这样设置)
  add-proxy-headers: true  #X-Forwarder-Host请求头默认添加到转发请求中
#  ignoreSecurityHeaders: false
  routes:
    auth:
      path: /auth/**
#      sensitive-headers:
      stripPrefix: true
      serviceId: microservice-store-auth
      sensitiveHeaders:
    admin:
      path: /admin/**
      serviceId: microservice-store-web-admin
      sensitiveHeaders:
    user:
      path: /user/**
      stripPrefix: false
      serviceId: microservice-store-service-user
      sensitiveHeaders:
    product:
      path: /product/**
      stripPrefix: false
      serviceId: microservice-store-service-product
      sensitiveHeaders:
#  add-proxy-headers: true
#  add-host-header: true
#  sensitive-headers:
#  custom-sensitive-headers: true
#zuul.sensitiveHeaders: Cookie,Set-Cookie,Authorization # zuul.sensitive-headers=

client:
  secret: store

while-list:
  uriWhiteList:
#    - /admin/login
#    - /admin/menu/list
#    - /user/menu/list
#    - /auth/oauth/token
#    - /auth/oauth/authorize
#    - /auth/oauth/user
#    - /auth/client/token
    - /auth/jwt/token




#security:
##  basic:
##    enabled: false
#  oauth2:
#    client:
#      access-token-uri: http://localhost:8888/auth/oauth/token
#      user-authorization-uri: http://localhost:8888/auth/oauth/authorize
#      client-id: webapp
##      client-id: eagleeye
##      client-secret: thisissecret
#    resource:
#      user-info-uri:  http://localhost:8888/auth/user
#      prefer-token-info: false
#
#
#endpoints:
#  restart:
#    enabled: true

#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 70000

