server:
  port: 8888

spring:
  application:
    name: microservice-store-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: microservice-store-web-admin
    user:
      path: /user/**
      stripPrefix: false
      serviceId: microservice-store-service-user


#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false
