server:
  port: 8888

spring:
  application:
    name: microservice-store-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    admin1:
      path: /store-admin/**
      #url: http://localhost:8777
      serviceId: microservice-store-web-admin
    #admin2:
      #path: /store-user/**
        #url: http://localhost:8777
      #serviceId: microservice-store-service-user

#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false
