server:
  port: 8888

spring:
  application:
    name: msa-store-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    admin:
      path: /store-admin/**
      #url: http://localhost:8777
      serviceId: msa-store-admin
    admin:
      path: /store-user/**
        #url: http://localhost:8777
      serviceId: msa-store-user

#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false
