spring:
  application:
    name: zuul-server

server:
  port: 8001

eureka:
  instance:
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: register.center.com
    server:
      port: 8051
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.server.port}/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign