server:
  port: 8999

spring:
  application:
    name: microservice-store-service-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&amp;characterEncoding=UTF-8
    username: yqqyyq
    password: yqqyyqM17
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  dbcp2:
    initial-size: 7
    max-total: 20
    pool-prepared-statements: true
  platform: mysql

mybatis:
  type-aliases-package: com.application.entity
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

