server:
  port: 8101

spring:
  application:
    name: msa-store-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&amp;characterEncoding=UTF-8
    username: store
    password: store
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  dbcp2:
    initial-size: 7
    max-total: 20
    pool-prepared-statements: true
  platform: mysql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#mybatis:
#  type-aliases-package: com.application.entity
#  config-locations: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml

